package model;
// Generated 18 dic 2023 18:28:04 by Hibernate Tools 6.3.1.Final

import java.sql.Date;

/**
 * Resenas generated by hbm2java
 */
public class Resenas implements java.io.Serializable {

	private Integer id;
	private Series series;
	private Anime anime;
	private Peliculas peliculas;
	private int valoracionResena;
	private String comentarioResena;
	private Date fechaResena;
	private String tipoResena;

	public Resenas() {
	}

	public Resenas(Series series, Anime anime, Peliculas peliculas, int valoracionResena, String comentarioResena,
			Date fechaResena, String tipoResena) {
		this.series = series;
		this.anime = anime;
		this.peliculas = peliculas;
		this.valoracionResena = valoracionResena;
		this.comentarioResena = comentarioResena;
		this.fechaResena = fechaResena;
		this.tipoResena = tipoResena;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Series getSeries() {
		return this.series;
	}

	public void setSeries(Series series) {
		this.series = series;
	}

	public Anime getAnime() {
		return this.anime;
	}

	public void setAnime(Anime anime) {
		this.anime = anime;
	}

	public Peliculas getPeliculas() {
		return this.peliculas;
	}

	public void setPeliculas(Peliculas peliculas) {
		this.peliculas = peliculas;
	}

	public int getValoracionResena() {
		return this.valoracionResena;
	}

	public void setValoracionResena(int valoracionResena) {
		this.valoracionResena = valoracionResena;
	}

	public String getComentarioResena() {
		return this.comentarioResena;
	}

	public void setComentarioResena(String comentarioResena) {
		this.comentarioResena = comentarioResena;
	}

	public Date getFechaResena() {
		return this.fechaResena;
	}

	public void setFechaResena(Date fechaResena) {
		this.fechaResena = fechaResena;
	}

	public String getTipoResena() {
		return this.tipoResena;
	}

	public void setTipoResena(String tipoResena) {
		this.tipoResena = tipoResena;
	}

}
