package model;
// Generated 18 dic 2023 18:28:04 by Hibernate Tools 6.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String contrasena;
	private String email;
	private Set animes = new HashSet(0);
	private Set peliculases = new HashSet(0);
	private Set serieses = new HashSet(0);

	public Usuarios() {
	}

	public Usuarios(String nombre, String contrasena, String email, Set animes, Set peliculases, Set serieses) {
		this.nombre = nombre;
		this.contrasena = contrasena;
		this.email = email;
		this.animes = animes;
		this.peliculases = peliculases;
		this.serieses = serieses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getContrasena() {
		return this.contrasena;
	}

	public void setContrasena(String contrasena) {
		this.contrasena = contrasena;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Set getAnimes() {
		return this.animes;
	}

	public void setAnimes(Set animes) {
		this.animes = animes;
	}

	public Set getPeliculases() {
		return this.peliculases;
	}

	public void setPeliculases(Set peliculases) {
		this.peliculases = peliculases;
	}

	public Set getSerieses() {
		return this.serieses;
	}

	public void setSerieses(Set serieses) {
		this.serieses = serieses;
	}

}
