/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.ListarResenasAnime;
import controller.ListarResenasPeliculas;
import controller.listarPeliculasUtil;
import controller.loginUtil;
import javax.swing.JPanel;


/**
 *
 * @author Alumno
 */
public class listarResenasAnimep extends javax.swing.JPanel {

    /**
     * Creates new form ListarPeliculas
     */
    ListarResenasAnime listar = new ListarResenasAnime();
    loginUtil login = new loginUtil();
    
    public listarResenasAnimep() {
        initComponents();
        int id = login.getIdUsuarioActual();
        
        listar.mostrarResenas(panelListarresenasAnime);
          
    }
    


    public JPanel obtenerPanelPeliculas() {
        return panelListarresenasAnime;
    }


                  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelListarresenasAnime = new javax.swing.JPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        panelListarresenasAnime.setLayout(new javax.swing.BoxLayout(panelListarresenasAnime, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(panelListarresenasAnime);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 730));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelListarresenasAnime;
    // End of variables declaration//GEN-END:variables
}

