/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.HibernateUtil;
import java.awt.BorderLayout;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import model.Peliculas;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.SessionFactory;

/**
 *
 * @author Alumno
 */
public class ListarPeliculas extends javax.swing.JPanel {

    /**
     * Creates new form ListarPeliculas
     */
    public ListarPeliculas() {
        initComponents();
          mostrarPeliculas();
          
    }
    
     private void mostrarPeliculas() {
        // Obtener la lista de películas desde la base de datos
        List<Peliculas> peliculas = obtenerPeliculasDesdeBD();

        // Crear el panel principal que contiene los paneles de películas
        JPanel PanelPeliculas = new JPanel();
        PanelPeliculas.setLayout(new BoxLayout(PanelPeliculas, BoxLayout.Y_AXIS));

        // Agregar un PanelPeliculas por cada película
        for (Peliculas pelicula : peliculas) {
            PanelPeliculas panelPeliculas = new PanelPeliculas();
            llenarPanelConPelicula(panelPeliculas, pelicula);
            PanelPeliculas.add(panelPeliculas);
            jPanel1.add(panelPeliculas);
        }

        // Crear JScrollPane y agregar el panel de películas
        JScrollPane jScrollPane = new JScrollPane(PanelPeliculas);

        // Agregar el JScrollPane al panel principal
        add(jScrollPane, BorderLayout.CENTER);
    }

    private List<Peliculas> obtenerPeliculasDesdeBD() {
        // Recuperar datos de la base de datos usando HibernateUtil
        SessionFactory sessionFactory = HibernateUtil.getSessionFactory();
        Session session = sessionFactory.openSession();

        // Usar una consulta HQL para obtener las películas
        Query<Peliculas> query = session.createQuery("FROM Peliculas", Peliculas.class);
        List<Peliculas> peliculas = query.getResultList();
        System.out.println(peliculas.size());

        // Cerrar la sesión de Hibernate
        session.close();

        return peliculas;
    }

    private void llenarPanelConPelicula(PanelPeliculas panelPeliculas, Peliculas pelicula) {
        // Llenar el PanelPeliculas con la información de la película
        
        panelPeliculas.getlblTitulo().setText(pelicula.getTituloPelicula());
        panelPeliculas.getlblDirector().setText(pelicula.getDirectorPelicula());
        panelPeliculas.gettxtResumen().setText(pelicula.getResumenPelicula());
    }

                  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}

