/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.listarPeliculasUtil;
import controller.loginUtil;
import javax.swing.JPanel;


/**
 *
 * @author Alumno
 */
public class ListarPeliculas extends javax.swing.JPanel {

    /**
     * Creates new form ListarPeliculas
     */
    listarPeliculasUtil listar = new listarPeliculasUtil();
    loginUtil login = new loginUtil();
    
    public ListarPeliculas() {
        initComponents();
        int id = login.getIdUsuarioActual();
        
        listar.mostrarPeliculas(panelListarPeliculas, id);
          
    }
    


    public JPanel obtenerPanelPeliculas() {
        return panelListarPeliculas;
    }


                  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelListarPeliculas = new javax.swing.JPanel();

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        panelListarPeliculas.setLayout(new javax.swing.BoxLayout(panelListarPeliculas, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(panelListarPeliculas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelListarPeliculas;
    // End of variables declaration//GEN-END:variables
}

