/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import controller.loginUtil;
import javax.swing.Icon;

/**
 *
 * @author alexg
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        botonAnadir.putClientProperty("JButton.buttonType", "square");
        botonAnime.putClientProperty("JButton.buttonType", "square");
        botonListado.putClientProperty("JButton.buttonType", "square");
        botonPeliculas.putClientProperty("JButton.buttonType", "square");
        botonResenas.putClientProperty("JButton.buttonType", "square");
        botonSeries.putClientProperty("JButton.buttonType", "square");
        botonSesion.putClientProperty("JButton.buttonType", "square");
        
        Icon leadingIcon1 = new FlatSVGIcon("img/bookmarkGroup.svg");
        Icon leadingIcon = new FlatSVGIcon("img/user.svg");
        
        
        botonSesion.putClientProperty("JTextField.leadingIcon", leadingIcon );
        botonListado.putClientProperty("JTextField.leadingIcon", leadingIcon1 );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        botonSesion = new javax.swing.JToggleButton();
        botonAnadir = new javax.swing.JToggleButton();
        botonListado = new javax.swing.JToggleButton();
        botonResenas = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        botonPeliculas = new javax.swing.JToggleButton();
        botonAnime = new javax.swing.JToggleButton();
        botonSeries = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonSesion.setBackground(new java.awt.Color(153, 153, 153));
        botonSesion.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        botonSesion.setText("Cerrar sesion");
        botonSesion.setBorder(null);
        jPanel2.add(botonSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 750, 180, 29));

        botonAnadir.setBackground(new java.awt.Color(153, 153, 153));
        botonAnadir.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        botonAnadir.setText("Añadir");
        botonAnadir.setBorder(null);
        jPanel2.add(botonAnadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 180, 29));

        botonListado.setBackground(new java.awt.Color(153, 153, 153));
        botonListado.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        botonListado.setText("Listado");
        botonListado.setBorder(null);
        jPanel2.add(botonListado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 180, 29));

        botonResenas.setBackground(new java.awt.Color(153, 153, 153));
        botonResenas.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        botonResenas.setText("Reseñas");
        botonResenas.setBorder(null);
        jPanel2.add(botonResenas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 180, 29));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 800));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonPeliculas.setBackground(new java.awt.Color(153, 153, 153));
        botonPeliculas.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        botonPeliculas.setText("Peliculas");
        botonPeliculas.setBorder(null);
        jPanel3.add(botonPeliculas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 70));

        botonAnime.setBackground(new java.awt.Color(153, 153, 153));
        botonAnime.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        botonAnime.setText("Anime");
        botonAnime.setBorder(null);
        jPanel3.add(botonAnime, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 360, 70));

        botonSeries.setBackground(new java.awt.Color(153, 153, 153));
        botonSeries.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        botonSeries.setText("Series");
        botonSeries.setBorder(null);
        jPanel3.add(botonSeries, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 360, 70));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 1080, 70));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 1080, 730));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        com.formdev.flatlaf.intellijthemes.FlatArcOrangeIJTheme.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton botonAnadir;
    private javax.swing.JToggleButton botonAnime;
    private javax.swing.JToggleButton botonListado;
    private javax.swing.JToggleButton botonPeliculas;
    private javax.swing.JToggleButton botonResenas;
    private javax.swing.JToggleButton botonSeries;
    private javax.swing.JToggleButton botonSesion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
