/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import controller.ajustarImagen;
import controller.loginUtil;
import java.awt.Color;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import controller.toggleUtil;
import java.rmi.server.UID;

/**
 *
 * @author alexg
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        UIManager.put("ToggleButton.selectedForeground", new Color(255, 255, 255));
        UIManager.put("ToggleButton.selectedBackground", new Color(255, 51, 51));
        UIManager.put("JButton.buttonType", "square");
        
        initComponents();
        
        ImageIcon logo = ajustarImagen.cargarYAjustarImagen("src\\main\\resources\\img\\logo.png", 65, 55);
        lbllogo.setIcon(logo);
        
        ImageIcon logoletra = ajustarImagen.cargarYAjustarImagen("src\\main\\resources\\img\\letraslogo.png", 120, 30);
        labelLogotxt.setIcon(logoletra);
        
        lbliconoUser.setIcon(new FlatSVGIcon("img/user.svg",15,17));
        lbliconoAnadir.setIcon(new FlatSVGIcon("img/add.svg",15,15));
        lbliconoList.setIcon(new FlatSVGIcon("img/list.svg",15,15));
        lbliconoResena.setIcon(new FlatSVGIcon("img/star.svg",15,15));
        
        botonAnadir.setSelected(true);
        botonPeliculas.setSelected(true);
        
        PanelInsertarPeliculas inicio = new PanelInsertarPeliculas();
        inicio.setSize(1144, 797);
        inicio.setLocation(0,0);
        
        llamarpanel(inicio);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoDash = new javax.swing.ButtonGroup();
        grupoSuperior = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        botonPeliculas = new controller.toggleUtil();
        botonAnime = new javax.swing.JToggleButton();
        botonSeries = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbliconoUser = new javax.swing.JLabel();
        lbliconoList = new javax.swing.JLabel();
        lbliconoAnadir = new javax.swing.JLabel();
        lbliconoResena = new javax.swing.JLabel();
        botonAnadir = new javax.swing.JToggleButton();
        botonListado = new controller.toggleUtil();
        botonResenas = new javax.swing.JToggleButton();
        lbllogo = new javax.swing.JLabel();
        labelLogotxt = new javax.swing.JLabel();
        botonSesion = new javax.swing.JToggleButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        grupoSuperior.add(botonPeliculas);
        botonPeliculas.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        botonPeliculas.setForeground(new java.awt.Color(255, 51, 51));
        botonPeliculas.setText("Peliculas");
        botonPeliculas.setBorder(null);
        botonPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPeliculasActionPerformed(evt);
            }
        });
        jPanel3.add(botonPeliculas, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 0, 361, 67));

        grupoSuperior.add(botonAnime);
        botonAnime.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        botonAnime.setForeground(new java.awt.Color(255, 51, 51));
        botonAnime.setText("Anime");
        botonAnime.setBorder(null);
        botonAnime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAnimeActionPerformed(evt);
            }
        });
        jPanel3.add(botonAnime, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 0, 361, 67));

        grupoSuperior.add(botonSeries);
        botonSeries.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        botonSeries.setForeground(new java.awt.Color(255, 51, 51));
        botonSeries.setText("Series");
        botonSeries.setBorder(null);
        botonSeries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSeriesActionPerformed(evt);
            }
        });
        jPanel3.add(botonSeries, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 0, 361, 67));

        jPanel4.setBackground(new java.awt.Color(255, 51, 51));
        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 67, 1083, 3));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 1090, 70));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(lbliconoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 767, 15, 15));
        jPanel2.add(lbliconoList, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 127, 15, 15));
        jPanel2.add(lbliconoAnadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 157, 15, 15));
        jPanel2.add(lbliconoResena, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 187, 15, 15));

        grupoDash.add(botonAnadir);
        botonAnadir.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        botonAnadir.setForeground(new java.awt.Color(255, 51, 51));
        botonAnadir.setText("Añadir");
        botonAnadir.setBorder(null);
        botonAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAnadirActionPerformed(evt);
            }
        });
        jPanel2.add(botonAnadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 217, 30));

        grupoDash.add(botonListado);
        botonListado.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        botonListado.setForeground(new java.awt.Color(255, 51, 51));
        botonListado.setText("Listado");
        botonListado.setBorder(null);
        botonListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListadoActionPerformed(evt);
            }
        });
        jPanel2.add(botonListado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 217, 30));

        grupoDash.add(botonResenas);
        botonResenas.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        botonResenas.setForeground(new java.awt.Color(255, 51, 51));
        botonResenas.setText("Reseñas");
        botonResenas.setBorder(null);
        botonResenas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonResenasActionPerformed(evt);
            }
        });
        jPanel2.add(botonResenas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 217, 30));

        lbllogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        jPanel2.add(lbllogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 0, 60, 50));

        labelLogotxt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelLogotxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letraslogo.png"))); // NOI18N
        jPanel2.add(labelLogotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 50, 120, 30));

        botonSesion.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        botonSesion.setForeground(new java.awt.Color(255, 51, 51));
        botonSesion.setText("Cerrar sesion");
        botonSesion.setBorder(null);
        botonSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSesionActionPerformed(evt);
            }
        });
        jPanel2.add(botonSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 760, 217, 30));

        jPanel5.setBackground(new java.awt.Color(255, 51, 51));
        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 70, 3, 730));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 800));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 1080, 730));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListadoActionPerformed
     if (botonPeliculas.isSelected()){
        
        ListarPeliculas listarPeliculas = new ListarPeliculas();
        listarPeliculas.setSize(1144, 797);
        listarPeliculas.setLocation(0,0);
        
        llamarpanel(listarPeliculas);
     }else if(botonSeries.isSelected()){
        ListarSeries listarSeries = new ListarSeries();
        listarSeries.setSize(1144, 797);
        listarSeries.setLocation(0,0);
        
        llamarpanel(listarSeries);
         
     }else if(botonAnime.isSelected()){
         ListarAnime listarAnime = new ListarAnime();
        listarAnime.setSize(1144, 797);
        listarAnime.setLocation(0,0);
        
        llamarpanel(listarAnime);
     }
    }//GEN-LAST:event_botonListadoActionPerformed

    private void botonSeriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSeriesActionPerformed
       
        
        if (botonAnadir.isSelected()){
        
        panelInsertarSeries insertarSeries = new panelInsertarSeries();
        insertarSeries.setSize(1144, 797);
        insertarSeries.setLocation(0,0);
        
        llamarpanel(insertarSeries);
        }else if(botonListado.isSelected()){
         ListarSeries listarSeries = new ListarSeries();
        listarSeries.setSize(1144, 797);
        listarSeries.setLocation(0,0);
        
        llamarpanel(listarSeries); 
        }else {
            
        }
    }//GEN-LAST:event_botonSeriesActionPerformed

    private void botonPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPeliculasActionPerformed
       
        if (botonAnadir.isSelected()){
        
        PanelInsertarPeliculas insertarPeliculas = new PanelInsertarPeliculas();
        insertarPeliculas.setSize(1144, 797);
        insertarPeliculas.setLocation(0,0);
        
        llamarpanel(insertarPeliculas);
        }else if (botonListado.isSelected()){
        
         ListarPeliculas listarPeliculas = new ListarPeliculas();
        listarPeliculas.setSize(1144, 797);
        listarPeliculas.setLocation(0,0);
        
        llamarpanel(listarPeliculas);
        }
    }//GEN-LAST:event_botonPeliculasActionPerformed

    private void botonAnimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAnimeActionPerformed
      
        if (botonAnadir.isSelected()){
        
        PanelInsertarAnime insertarAnime = new PanelInsertarAnime();
        insertarAnime.setSize(1144, 797);
        insertarAnime.setLocation(0,0);
        
        llamarpanel(insertarAnime);
        }else if (botonListado.isSelected()){
        
         ListarAnime listarAnime = new ListarAnime();
        listarAnime.setSize(1144, 797);
        listarAnime.setLocation(0,0);
        
        llamarpanel(listarAnime);
        }
    }//GEN-LAST:event_botonAnimeActionPerformed

    private void botonAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAnadirActionPerformed
      if (botonPeliculas.isSelected()){
        
        PanelInsertarPeliculas insertarPeliculas = new PanelInsertarPeliculas();
        insertarPeliculas.setSize(1144, 797);
        insertarPeliculas.setLocation(0,0);
        
        llamarpanel(insertarPeliculas);
     }else if(botonSeries.isSelected()){
        panelInsertarSeries insertarSeries = new panelInsertarSeries();
        insertarSeries.setSize(1144, 797);
        insertarSeries.setLocation(0,0);
        
        llamarpanel(insertarSeries);
         
     }else if(botonAnime.isSelected()){
         PanelInsertarAnime insertarAnime = new PanelInsertarAnime();
        insertarAnime.setSize(1144, 797);
        insertarAnime.setLocation(0,0);
        
        llamarpanel(insertarAnime);
     }
    }//GEN-LAST:event_botonAnadirActionPerformed

    private void botonResenasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonResenasActionPerformed
      
    }//GEN-LAST:event_botonResenasActionPerformed

    private void botonSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSesionActionPerformed
    abrirVentanaLogin();
    loginUtil login = new loginUtil();
    login.cerrarsesion();
    }//GEN-LAST:event_botonSesionActionPerformed

        private void abrirVentanaLogin() {
            
        login loginFrame = new login();

        loginFrame.setLocationRelativeTo(this);

        loginFrame.setVisible(true);
        dispose();
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        com.formdev.flatlaf.intellijthemes.FlatArcOrangeIJTheme.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    private void llamarpanel(JPanel panel){
        jScrollPane1.removeAll();
        jScrollPane1.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));  
        jScrollPane1.revalidate();
        jScrollPane1.repaint();
    
    
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton botonAnadir;
    private javax.swing.JToggleButton botonAnime;
    private javax.swing.JToggleButton botonListado;
    private javax.swing.JToggleButton botonPeliculas;
    private javax.swing.JToggleButton botonResenas;
    private javax.swing.JToggleButton botonSeries;
    private javax.swing.JToggleButton botonSesion;
    private javax.swing.ButtonGroup grupoDash;
    private javax.swing.ButtonGroup grupoSuperior;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelLogotxt;
    private javax.swing.JLabel lbliconoAnadir;
    private javax.swing.JLabel lbliconoList;
    private javax.swing.JLabel lbliconoResena;
    private javax.swing.JLabel lbliconoUser;
    private javax.swing.JLabel lbllogo;
    // End of variables declaration//GEN-END:variables
}
