/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import controller.ajustarImagen;
import javax.swing.ImageIcon;
import controller.RegistroUtil;
import javax.swing.JOptionPane;
import org.jasypt.util.text.AES256TextEncryptor;
/**
 *
 * @author alexg
 */

public class registro extends javax.swing.JFrame {
    /**
     * Creates new form signup
     */
    public registro() {
        initComponents();
        ImageIcon icono = ajustarImagen.cargarYAjustarImagen("src\\main\\resources\\img\\fondo.jpg", 630, 800);
        ImageIcon logo = ajustarImagen.cargarYAjustarImagen("src\\main\\resources\\img\\logo.png", 120, 100);    
        // Establecer la imagen ajustada en el JLabel
        labelfondo.setIcon(icono);
        labellogo.setIcon(logo);
        botonVerpass.setIcon(new FlatSVGIcon("img/ojonoVer.svg",20,20));
        botonVerpassRep.setIcon(new FlatSVGIcon("img/ojonoVer.svg",20,20));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelfondo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        botonVerpass = new javax.swing.JToggleButton();
        botonVerpassRep = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtPasswrd = new javax.swing.JPasswordField();
        labellogo = new javax.swing.JLabel();
        txtPasswrdRep = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 129, -1, -1));

        labelfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.jpg"))); // NOI18N
        jPanel2.add(labelfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 800));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 800));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonVerpass.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        botonVerpass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVerpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerpassActionPerformed(evt);
            }
        });
        jPanel3.add(botonVerpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 470, 40, 40));

        botonVerpassRep.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        botonVerpassRep.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVerpassRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerpassRepActionPerformed(evt);
            }
        });
        jPanel3.add(botonVerpassRep, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 570, 40, 40));

        jLabel5.setBackground(new java.awt.Color(102, 102, 102));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Usuario");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, -1));

        txtUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(102, 102, 102));
        jPanel3.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 350, 40));

        jLabel6.setBackground(new java.awt.Color(102, 102, 102));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Email");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, -1, -1));

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(102, 102, 102));
        jPanel3.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 350, 40));
        txtEmail.getAccessibleContext().setAccessibleName("");

        jLabel7.setBackground(new java.awt.Color(102, 102, 102));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Repite la contraseña");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 540, 150, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Ya tienes cuenta?");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 760, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Registro");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 670, 91, 37));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 51, 51));
        jButton2.setText("Login");
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 755, 70, 31));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("REGISTRO");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, -1));

        txtPasswrd.setText("jPasswordField2");
        jPanel3.add(txtPasswrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 350, 40));

        labellogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        jPanel3.add(labellogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 120, 100));

        txtPasswrdRep.setText("jPasswordField2");
        jPanel3.add(txtPasswrdRep, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 570, 350, 40));

        jLabel9.setBackground(new java.awt.Color(102, 102, 102));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Contraseña");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 0, 670, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    abrirVentanaLogin();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nombreUsuario = txtUsuario.getText();
        String email = txtEmail.getText();
        String contrasena = new String(txtPasswrd.getPassword());
        String contrasena2 = new String(txtPasswrdRep.getPassword());
        
        if (!contrasena.equals(contrasena2)) {
            JOptionPane.showMessageDialog(this, "Por favor, las dos contraseñas tienen que ser iguales.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } 

        if (nombreUsuario.isEmpty() || email.isEmpty() || contrasena.isEmpty()) {

            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        


        AES256TextEncryptor encryptor = new AES256TextEncryptor();
        encryptor.setPassword("gfdasdfsghfdtert"); 
        String encryptedPassword = encryptor.encrypt(contrasena);

        boolean registroExitoso = RegistroUtil.registrarUsuario(nombreUsuario, email, encryptedPassword);

        if (registroExitoso) {
            JOptionPane.showMessageDialog(this, "Usuario registrado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Error al registrar el usuario.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botonVerpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerpassActionPerformed
        if (botonVerpass.isSelected()){
            txtPasswrd.setEchoChar((char)0);
            botonVerpass.setIcon(new FlatSVGIcon("img/ojoVer.svg",16,12));
            
        }else{
            txtPasswrd.setEchoChar('*');
            botonVerpass.setIcon(new FlatSVGIcon("img/ojonoVer.svg",20,20));
        }
    }//GEN-LAST:event_botonVerpassActionPerformed

    private void botonVerpassRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerpassRepActionPerformed
       if (botonVerpassRep.isSelected()){
            txtPasswrdRep.setEchoChar((char)0);
            botonVerpassRep.setIcon(new FlatSVGIcon("img/ojoVer.svg",16,12));
            
        }else{
            txtPasswrdRep.setEchoChar('*');
            botonVerpassRep.setIcon(new FlatSVGIcon("img/ojonoVer.svg",20,20));
        }
    }//GEN-LAST:event_botonVerpassRepActionPerformed
        private void abrirVentanaLogin() {
            
        login loginFrame = new login();

        loginFrame.setLocationRelativeTo(this);

        loginFrame.setVisible(true);
        dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(recordar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(recordar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(recordar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(recordar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton botonVerpass;
    private javax.swing.JToggleButton botonVerpassRep;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelfondo;
    private javax.swing.JLabel labellogo;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPasswrd;
    private javax.swing.JPasswordField txtPasswrdRep;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
